name: Deploy Models

on:
  push:
    tags:
      - 'v0.*'
      - 'draft-*'

env:
  CARGO_TERM_COLOR: always

jobs:
  DeployModel:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v5.2.0
    - uses: actions/checkout@v4.1.7
    - name: build chatglm.cpp
      run: ./environment/chatglm.cpp.sh
    - name: build llama.cpp
      run: ./environment/llama.cpp.sh
    - name: pull model
      run: ./chatglm/download-model.sh
    - name: quantize llama
      run: ./chatglm/quantize-mode-llama.sh
    - name: quantize chatglm
      run: ./chatglm/quantize-model-chatglm.sh
