name: Verify Building Environment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  WORK_PATH: ${{GITHUB_WORKSPACE}}/works

jobs:
  BuildingEnvironment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v5.2.0
    - uses: actions/checkout@v4.1.7
      with: 
        repository: "ggerganov/llama.cpp"
    - name: Verify ENV
      run: |
        echo WORK_PATH=$WORK_PATH
        ls -lha $GITHUB_WORKSPACE
    - name: Verify catglm.cpp Env
      run: |
        python3 -m pip install -U pip
        python3 -m pip install torch tabulate tqdm transformers accelerate sentencepiece
        python3 -m pip install tiktoken
    - name: Verify llama.cpp Env
      run: |
        sudo apt update && sudo apt install libopenblas-dev -y
        python3 -m pip install -r requirements.txt
    - name: Build llama.cpp
      run: make GGML_OPENBLAS=1 -j 8

      
